#!/usr/bin/env python

import sys
from os import listdir
import os.path
from optparse import OptionParser, OptionGroup

from cljob.opts import make_host_options,      \
                       make_output_options,    \
                       parse_host_cmd_options, \
                       make_output_handlers,   \
                       get_default_dir

from cljob import rsh
from cljob.job import UploadJob

def parse_dir_name(dname):
    chunks = dname.split(':', 1)
    if len(chunks) == 1:
        return dname, ''
    else:
        return chunks[0], chunks[1]

def main():
    optparser = OptionParser(usage="""
    """)

    output_options = OptionGroup(optparser, "Output options")
    output_options.add_options(make_output_options())
    optparser.add_option_group(output_options)
    rsh_options = OptionGroup(optparser, "Rsh options")
    rsh_options.add_options(rsh.make_options())
    optparser.add_option_group(rsh_options)

    options, args = optparser.parse_args(sys.argv[1:])
    if len(args) == 1:
        jobs_dir = args[0]
        base_path = ''
    elif len(args) == 2:
        jobs_dir, base_path = args
    else:
        optparser.error("You need to specify jobs dir and optional target base dir on remote hosts")

    # options.working_dir = get_default_dir(options.working_dir)

    jobs = []
    for dname in listdir(jobs_dir):
        host, path = parse_dir_name(dname)
        files = [os.path.join(jobs_dir, dname, '')]
        path = os.path.join(base_path, path)
        jobs.append(UploadJob(host, files, path))

    handlers = make_output_handlers(options, jobs)

    for job in rsh.run_upload_jobs(jobs, **rsh.parse_options(options)):
        for hnd in handlers:
            hnd(job)

    for hnd in handlers:
        if 'finish' in dir(hnd):
            hnd.finish()

if __name__ == '__main__':
    main()
